{% set name = "fvcore" %}
{% set version = "0.1.3.post20210213" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b186f787da1b8333b7a73ffb801682f01f1415fe8c96402bd12f9cb869165cf0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pillow
    - portalocker
    - python >=3.6
    - pyyaml >=5.1
    - tabulate
    - termcolor >=1.1
    - tqdm
    - yacs >=0.1.6

test:
  imports:
    - fvcore

about:
  home: https://github.com/facebookresearch/fvcore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE  # license file not included in pypi tarball, packaged in recipe
  summary: Collection of common code shared among different research projects in FAIR computer vision team
  doc_url: https://github.com/facebookresearch/fvcore
  dev_url: https://github.com/facebookresearch/fvcore

extra:
  recipe-maintainers:
    - rluria14
    - oblute
